events {}

http {
    upstream routers {
        server router:9000;
        server router2:9000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://routers;
        }
    }
}